import { ReservationRepository } from "../../repositories/ReservationRepository";
import { RoomRepository } from "../../repositories/RoomRepository";
import { UserRepository } from "../../repositories/UserRepository";
import { CheckInReservationController } from "./CheckInReservation/CheckInReservationController";
import { CheckInReservationUseCase } from "./CheckInReservation/CheckInReservationUseCase";
import { ConfirmReservationController } from "./ConfirmReservation/ConfirmReservationController";
import { ConfirmReservationUseCase } from "./ConfirmReservation/ConfirmReservationUseCase";
import { CreateReservationController } from "./CreateReservation/CreateReservationController";
import { CreateReservationUseCase } from "./CreateReservation/CreateReservationUseCase";
import { DownloadReservationController } from "./DownloadReservation/DownloadReservationController";
import { DownloadReservationUseCase } from "./DownloadReservation/DownloadReservationUseCase";
const reservationRepository = new ReservationRepository();
const userRepository = new UserRepository();
const roomRepository = new RoomRepository();
export const createReservationUseCase = new CreateReservationUseCase(reservationRepository, userRepository, roomRepository);
export const createReservationController = new CreateReservationController(createReservationUseCase);
export const confirmReservationUseCase = new ConfirmReservationUseCase(reservationRepository);
export const confirmReservationController = new ConfirmReservationController(confirmReservationUseCase);
export const downloadReservationUseCase = new DownloadReservationUseCase(reservationRepository);
export const downloadReservationController = new DownloadReservationController(downloadReservationUseCase);
export const checkInReservationUseCase = new CheckInReservationUseCase(reservationRepository, userRepository);
export const checkInReservationController = new CheckInReservationController(checkInReservationUseCase);